name: Build APK

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'File name being compiled'
        required: true
        default: 'main.al'
      code:
        description: 'AppLang source code'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Save code to file
        run: |
          echo "${{ github.event.inputs.code }}" > ${{ github.event.inputs.filename }}

      - name: Build APK with Gradle
        run: ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/*.apk

