name: Build Real APK

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'File name being compiled'
        required: true
        default: 'index.html'
      code:
        description: 'AppLang compiled HTML string'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Create Cordova Project & Inject Compiled App
        run: |
          cordova create appcom com.applang.app AppLang
          cd appcom
          cordova platform add android
          
          # Overwrite Cordova's default screen with the compiled HTML from IDE
          echo "${{ github.event.inputs.code }}" > www/index.html

          # Build debug APK
          cordova build android --no-telemetry

      - name: Upload Real APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: appcom/platforms/android/app/build/outputs/apk/debug/app-debug.apk

